M48
; DRILL file {KiCad 9.0.0} date 2025-07-22T14:39:17-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-22T14:39:17-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.300
%
G90
G05
T1
X122.465Y-77.36
X122.465Y-83.14
T2
X131.85Y-63.82
X134.85Y-63.82
T3
X139.555Y-99.565
X154.545Y-99.565
M30
